export const allRoutes = Object.freeze({
  HOME: "/",
  PORTAL: "/portal",
  LOGIN: "/login",
  DASHBOARD: "/dashboard",
  CUSTOMERS: "/customers",
  ADD_CUSTOMER: "/customers/new",
  UPDATE_CUSTOMER: (id: string) => `/customers/${id}`,
  AGENTS: "/agents",
  BILLINGS: "/billings",
  TICKETS: "/tickets",
  LEADS: "/leads",
  COMPLAINTS: "/complaints",
  ROLES: "/roles",
  ADD_ROLE: "/roles/new",
  UPDATE_ROLE: (id: string) => `/roles/${id}`,
  ENQUIRIES: "/enquiries",
  ANALYTICS: "/analytics",
  SETTINGS: "/settings",
  SOFTWARES: "/softwares",
  UNAUTHORIZED: "/unauthorized",
});
