
export const allRoutes = Object.freeze({
  HOME: "/",
  PORTAL: "/portal",
  LOGIN: "/login",
  VERIFICATION: "/verification",
  DASHBOARD: "/dashboard",
  CUSTOMERS: "/customers",
  ADD_CUSTOMER: "/customers/new",
  UPDATE_CUSTOMER: (id: string) => `/customers/${id}`,
  VIEW_CUSTOMER: (id: string) => `/customers/${id}`,
  SOFTWARES: "/softwares",
  ADD_SOFTWARE: "/softwares/new",
  UPDATE_SOFTWARE: (id: string) => `/softwares/${id}`,
  COMPLAINT_TYPES: "/complaint-types",
  ADD_COMPLAINT_TYPE: "/complaint-types/new",
  UPDATE_COMPLAINT_TYPE: (id: string) => `/complaint-types/${id}`,
  COMPLAINT_CATEGORIES: "/complaint-categories",
  ADD_COMPLAINT_CATEGORIES: "/complaint-categories/new",
  UPDATE_COMPLAINT_CATEGORIES: (id: string) => `/complaint-categories/${id}`,
  CALL_STATUSES: "/call-statuses",
  ADD_CALL_STATUS: "/call-statuses/new",
  UPDATE_CALL_STATUS: (id: string) => `/call-statuses/${id}`,
  SETUP_STATUSES: "/setup-statuses",
  ADD_SETUP_STATUS: "/setup-statuses/new",
  UPDATE_SETUP_STATUS: (id: string) => `/setup-statuses/${id}`,
  SUBSCRIPTION_TYPES: "/subscription-types",
  ADD_SUBSCRIPTION_TYPE: "/subscription-types/new",
  UPDATE_SUBSCRIPTION_TYPE: (id: string) => `/subscription-types/${id}`,
  LEAD_STATUSES: "/lead-statuses",
  ADD_LEAD_STATUS: "/lead-statuses/new",
  UPDATE_LEAD_STATUS: (id: string) => `/lead-statuses/${id}`,
  LEAD_NEXT_STEPS: "/lead-next-steps",
  ADD_LEAD_NEXT_STEP: "/lead-next-steps/new",
  UPDATE_LEAD_NEXT_STEP: (id: string) => `/lead-next-steps/${id}`,
  ROLES: "/roles",
  ADD_ROLE: "/roles/new",
  UPDATE_ROLE: (id: string) => `/roles/${id}`,
  DELETE_ROLE: (id: string) => `/roles/${id}`,
  VIEW_ROLE: (id: string) => `/roles/${id}/view`,
  USERS: "/users",
  ADD_USER: "/users/new",
  VIEW_USER: (id: string) => `/users/${id}/view`,
  UPDATE_USER: (id: string) => `/users/${id}`,
  DELETE_USER: (id: string) => `/users/${id}`,
  LEADS: "/leads",
  ADD_LEAD: "/leads/new",
  UPDATE_LEAD: (id: string) => `/leads/${id}`,
  VIEW_LEAD: (id: string) => `/leads/${id}/view`,
  COMPLAINTS: "/complaints",
  ADD_COMPLAINT: "/complaints/new",
  UPDATE_COMPLAINT: (id: string) => `/complaints/${id}`,
  VIEW_COMPLAINT: (id: string) => `/complaints/${id}/view`,
  OUT_REACH_TYPES: "/outreach-types",
  ADD_OUTREACH_TYPE: "/outreach-types/new",
  UPDATE_OUTREACH_TYPE: (id: string) => `/outreach-types/${id}`,
  DELETE_OUTREACH_TYPE: (id: string) => `/outreach-types/${id}`,
  VIEW_OUTREACH_TYPE: (id: string) => `/outreach-types/${id}/view`,
  ENQUIRIES: "/enquiries",
  ANALYTICS: "/analytics",
  AGENTS: "/agents",
  SUBSCRIPTIONS: "/subscriptions",
  ADD_SUBSCRIPTION: "/subscriptions/new",
  UPDATE_SUBSCRIPTION: (id: string) => `/subscriptions/${id}`,
  VIEW_SUBSCRIPTION: (id: string) => `/subscriptions/${id}/view`,
  ADD_SUBSCRIPTION_PAYMENT: (subscriptionId: string) =>
    `/subscriptions/${subscriptionId}/payment/new`,
  PAYMENTS: "/payments",
  VIEW_PAYMENT: (id: string) => `/payments/${id}/view`,
  TICKETS: "/tickets",
  SETTINGS: "/settings",
  UNAUTHORIZED: "/unauthorized",
  NOT_FOUND: "/not-found",
  CUSTOMER_OUTREACHS: "/customer-outreachs",
  ADD_CUSTOMER_OUTREACH: "/customer-outreachs/new",
  UPDATE_CUSTOMER_OUTREACH: (id: string) => `/customer-outreachs/${id}`,
  VIEW_CUSTOMER_OUTREACH: (id: string) => `/customer-outreachs/${id}/view`,
});

export const customerRoutes = Object.freeze({
  OVERVIEW: "/overview",
  DASHBOARD: "/dashboard",
  TICKETS: "/tickets",
  COMPLAINTS: "/complaints",
  ENQUIRIES: "/enquiries",
  PAYMENTS: "/payments",
  OUTREACHS: "/outreachs",
});
