export const allRoutes = Object.freeze({
  HOME: "/",
  PORTAL: "/portal",
  LOGIN: "/login",
  DASHBOARD: "/dashboard",
  CUSTOMERS: "/customers",
  AGENTS: "/agents",
  BILLINGS: "/billings",
  TICKETS: "/tickets",
  LEADS: "/leads",
  COMPLAINTS: "/complaints",
  ENQUIRIES: "/enquiries",
  ANALYTICS: "/analytics",
  SETTINGS: "/settings",
  SOFTWARES: "/softwares",
  UNAUTHORIZED: "/unauthorized",
});
