name: PR Build & Check

on:
  pull_request:
    branches:
      - master
      

jobs:
  build:
    name: Build & Validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      #- name: Lint
       # run: |
          #if yarn run | grep -q "lint"; then
           # yarn lint
          #else
            #echo "No lint script found, skipping..."
          #fi

      - name: Run tests
        run: |
          if yarn run | grep -q "test"; then
           yarn test -- --run
          else
            echo "No test script found, skipping..."
          fi

      - name: Build project
        run: npm run build
